### ISSUE TITLE
toolbar not showing up

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/mapknitter#256]
### What happened just before the problem occurred
I haven't been able to get the toolbar to show up when I'm editing maps. I can use the command keys, but I'd like to see the toolbar again (plus you can't delete images with the command keys). This is all I get when I click on the map image: 

<img width="1231" alt="screen shot 2018-03-16 at 11 52 20 am" src="https://user-images.githubusercontent.com/7490478/37533737-bfc4a378-2910-11e8-8c5f-dc4418d4b9f7.png">

### Relevant URLs

https://mapknitter.org/maps/test-new-orleans

### PublicLab.org username 
Stevie

### Browser, version, and operating system
Mac: OS X Yosemite 
I'm working on Chrome Version 64.0.3282.167 (Official Build) (64-bit)

**Comment by jywarren** [comment]
Thanks, great catch. This is supposed to be working for sure... i've checked the version numbers and asked Sebastian to try rebooting the server to see. I think something went wrong with the version of the mapping library we're using (it was just updated a month or so ago). Not sure how!

**Comment by icarito** [comment]
Hi,
I've completed deployment of this and confirmed it is fixed. Thanks!

**Comment by icarito** [comment]
This is the toolbar, to confirm:
![image](https://user-images.githubusercontent.com/199755/37579911-efeaaab6-2b0e-11e8-9a8b-e47b3887799c.png)

**Comment by jywarren** [comment]
awesome, thanks a million, Sebastian!

**Comment by jywarren** [comment]
Hmm, I just tested successfully on my Firefox browser on my phone... Can u
try in an incognito window?

**Comment by steviepubliclab** [comment]
i'm on a different computer now, and am getting it to work on chrome now. I
still don't think it's working on the other computer though.

**Comment by jywarren** [comment]
That's unfortunate! If you could try in an incognito window on the computer where it's not working, that would help -- thank you!

**Comment by steviepubliclab** [comment]
Seems to be working now!

**Comment by jywarren** [comment]
awesome, thanks a lot for checking!

**Comment by steviepubliclab** [comment]
Hi running a workshop right now and no one here is able to get the toolbar on mapknitter again. We're all on macs and we're all using chrome (version66)

**Comment by jywarren** [comment]
Are you clicking twice on the image? I just tested on chrome 66 on Mac and
it worked, so I'm trying to figure out what's going on! Can you make a
screen video or licecap gif? Sorry that's frustrating!

**Comment by jywarren** [comment]
I believe this was solved (again) here: https://github.com/publiclab/Leaflet.DistortableImage/issues/99
