### ISSUE TITLE
Support: Installation Issues with MapKnitter

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/mapknitter#307]
Facing trouble installing Mapknitter? We are here to help you.

**Comment by Dhiraj240** [comment]
@SidharthBansal After tackling to much issues and setting up ubuntu on vmware, today i was able to manage things.
But a small error is coming as when i use ```curl -L https://get.rvm.io | bash -s stable``` it asks for a key and there i am getting ```timeout error ``` which is annoying me.
Need Help !

**Comment by SidharthBansal** [comment]
Same behaviour here. Trying to debug.

**Comment by Dhiraj240** [comment]
@SidharthBansal Have you found the solution @jywarren  can you provide us help with this?

**Comment by kaunair** [comment]
Does the docker container work properly?
I'm getting an error while building it.

`ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get update -qqe-dev ruby-dev gdal-bin python-gdal curl libcurl4-openssl-dev libssl-dev zip nod`

**Comment by jywarren** [comment]
oh, hmm, maybe this is a question for @icarito - but the docker container
should be used in Travis, and that is building currently. Can you add more
information from the error you saw, maybe a fuller log shared in
gist.github.com? Thanks!

**Comment by Dhiraj240** [comment]
Thanks it worked @jywarren  but now when i ran ```bundle exec rake db:setup``` it asked me a root password which didn't work for mysql and it is throwing an error.
I looked stack overflow and other sites but they to haven't solved the issue.
May i know as how can i see or check the root password in ubuntu ? 
Although i will check this again in morning.

**Comment by kaunair** [comment]
[Here](https://gist.github.com/kaunair/ffd8f41abdc6d9a5d495c0877636d245) is a larger error log
I was trying to build the container using docker compose

**Comment by gauravano** [comment]
Hi @Dhiraj240, you can reset the password using - https://dev.mysql.com/doc/refman/8.0/en/resetting-permissions.html 

And, if you still get error - `ERROR 1698 (28000): Access denied for user 'root'@'localhost'" error` then, checkout this thread - https://stackoverflow.com/questions/39281594/error-1698-28000-access-denied-for-user-rootlocalhost. 

I also faced some of these issues but finally able to resolve them.Thanks!

**Comment by icarito** [comment]
@kaunair please check that you have a recent version of Docker. I found a related issue to your log at https://github.com/Shippable/support/issues/4398 and it was an old Docker version! Try it and let us know, also tell us what command did you run exactly, thanks!

**Comment by icarito** [comment]
@Dhiraj240 about the MySQL root password if you mean from the container it can be seen in the mysql logs: `docker-compose logs db` on _first run_.

**Comment by niravasher** [comment]
On entering "bundle exec rake db:setup"
Getting the error "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
rake aborted!
Mysql2::Error: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by niravasher** [comment]
after bundle install
sudo service mysql start
bundle exec rake db:setup    gives Access denied for user 'mapknitter'@'localhost' (using password: YES).
Please provide the root password for your mysql installation
>'some random password'
rake aborted!
Mysql2::Error: Access denied for user 'root'@'localhost' (using password: YES) 
(I already have set root password for mysql while installing sudo apt-get mysql-server)

**Comment by jywarren** [comment]
Hi, have you configured the passwords and usernames in
/config/database.yml?

**Comment by niravasher** [comment]
Yes, I confirmed they are same. I atried to uninstall and reinstall mysql-server, everything went fine just the last step bundle exec passenger start gave me this 
"Message from application: Address already in use - listen(2) (Errno::EADDRINUSE)"
I tried looking over stack overflow, but I didn't find anything in my local running on port 3000

**Comment by jywarren** [comment]
Hm, it may be that you are already running the server in another terminal
window... but that doesn't address the mysql issue. Are you able to log in
manually to mysql using `mysql -u root -p PASSWORD` without trouble? And
can you share your database.yml (but please strip out the PASSWORD field
itself!)?

**Comment by niravasher** [comment]
![screenshot 25](https://user-images.githubusercontent.com/32176296/52787334-7eefbb00-3083-11e9-9bb2-c5176a046f40.png)
![screenshot 26 _li](https://user-images.githubusercontent.com/32176296/52787447-e0b02500-3083-11e9-9fd9-407230c951f7.jpg)

**Comment by gauravano** [comment]
I gave different names to database in development and in testing:

![database yml](https://user-images.githubusercontent.com/20878070/52810737-3f43c600-30b9-11e9-850d-9a8395e67df4.png)

**Comment by gauravano** [comment]
I faced somewhat similar errors initially, I tried resetting password too but at last I changed the mysql plugin to `mysql_native_password` instead of `auth_socket` using - https://stackoverflow.com/questions/39281594/error-1698-28000-access-denied-for-user-rootlocalhost

You can do this on non-root user but changing plugin for root user is really upto you.

**Comment by niravasher** [comment]
Now running "bundle exec passenger start" gives this error
Message from application: Address already in use - listen(2) (Errno::EADDRINUSE)

**Comment by gauravano** [comment]
you can run the rails server on a different port with `rails s -p [port-number]` . Also, it's fine to start with default server WebRick for development(when you run server with rails s, webrick is used by default) and you can go with passenger after some time.  

Thanks!

**Comment by jywarren** [comment]
Hi, all, thanks to @gauravano and @sashadev-sky we are now on Ruby 2.4.4: https://github.com/publiclab/mapknitter/pull/320

**Comment by Dhiraj240** [comment]
@jywarren @gauravano  Now, i am getting the following error
```
bundle exec rake db:setup
rake aborted!
NoMethodError: undefined method `active_record' for #<Rails::Application::Configuration:0x0000556569694a78>
/home/dhiraj/.rvm/gems/ruby-2.4.4/gems/railties-3.2.22.5/lib/rails/railtie/configuration.rb:85:in `method_missing'
/home/dhiraj/mapknitter/config/application.rb:55:in `<class:Application>'
/home/dhiraj/mapknitter/config/application.rb:13:in `<module:Mapknitter>'
/home/dhiraj/mapknitter/config/application.rb:12:in `<top (required)>'
/home/dhiraj/mapknitter/Rakefile:5:in `require'
/home/dhiraj/mapknitter/Rakefile:5:in `<top (required)>'
/home/dhiraj/.rvm/gems/ruby-2.4.4/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/dhiraj/.rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:24:in `eval'
/home/dhiraj/.rvm/gems/ruby-2.4.4/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
```
I tried the database configuration given in the above screenshots.

**Comment by Dhiraj240** [comment]
Although i ran ```bundle update``` but this problem still persists.

**Comment by gauravano** [comment]
Hey @Dhiraj240, which database config you used, please point to the comment?

**Comment by Dhiraj240** [comment]
> I gave different names to database in development and in testing:
> 
> ![database yml](https://user-images.githubusercontent.com/20878070/52810737-3f43c600-30b9-11e9-850d-9a8395e67df4.png)

this one

**Comment by cesswairimu** [comment]
Was having trouble with mysql was throwing this error `ERROR 1698 (28000): Access denied for user 'root'@'localhost'" error` even after following the above steps. What worked for me was removing mysql and deleting mysql user and doing a fresh installation so I can setup a password. Here are the steps i followed
```
sudo -i
service mysql stop
killall -KILL mysql mysqld_safe mysqld
apt-get --yes purge mysql-server mysql-client
apt-get --yes autoremove --purge
apt-get autoclean
deluser --remove-home mysql
delgroup mysql
rm -rf /etc/apparmor.d/abstractions/mysql /etc/apparmor.d/cache/usr.sbin.mysqld /etc/mysql /var/lib/mysql /var/log/mysql* /var/log/upstart/mysql.log* /var/run/mysqld
updatedb
exit
```

**Comment by sashadev-sky** [comment]
Thank you @cesswairimu!! Would you be interested in adding this to the `MYSQL.md` file? And any setup recommendations / instructions you have for your OS? Currently we only have steps there for MacOS

**Comment by cesswairimu** [comment]
Hey @sashadev-sky, sure will do. Thanks

**Comment by cesswairimu** [comment]
Any fixes for this error `mapknitter/tmp/pids/passenger.3000.pid" failed (13: Permission denied)
    nginx: configuration file nginx.conf test failed` when starting the server

**Comment by emestabillo** [comment]
Hi @jywarren,
Thanks for responding! Here's my error again after trying to install the project locally. Posting everything just in case. This is while running `bundle`:

```
Using libv8 3.16.14.19 (x86_64-darwin-16)
Using mimemagic 0.3.0
Fetching mysql2 0.3.21
Installing mysql2 0.3.21 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/emmilie/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/mysql2-0.3.21/ext/mysql2
/Users/emmilie/.rbenv/versions/2.4.4/bin/ruby -r ./siteconf20190329-19328-191030x.rb extconf.rb
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for rb_thread_blocking_region()... no
checking for rb_wait_for_single_fd()... yes
checking for rb_hash_dup()... yes
checking for rb_intern3()... yes
-----
Using mysql_config at /usr/local/bin/mysql_config
-----
checking for mysql.h... yes
checking for errmsg.h... yes
checking for mysqld_error.h... yes
-----
Don't know how to set rpath on your system, if MySQL libraries are not in path mysql2 may not load
-----
-----
Setting libpath to /usr/local/Cellar/mysql/8.0.15/lib
-----
creating Makefile

current directory: /Users/emmilie/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/mysql2-0.3.21/ext/mysql2
make "DESTDIR=" clean

current directory: /Users/emmilie/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/mysql2-0.3.21/ext/mysql2
make "DESTDIR="
compiling client.c
client.c:439:3: error: use of undeclared identifier 'my_bool'
  my_bool res = mysql_read_query_result(client);
  ^
client.c:441:19: error: use of undeclared identifier 'res'
  return (void *)(res == 0 ? Qtrue : Qfalse);
                  ^
client.c:762:3: error: use of undeclared identifier 'my_bool'
  my_bool boolval;
  ^
client.c:793:7: error: use of undeclared identifier 'boolval'
      boolval = (value == Qfalse ? 0 : 1);
      ^
client.c:794:17: error: use of undeclared identifier 'boolval'
      retval = &boolval;
                ^
client.c:797:10: error: use of undeclared identifier 'MYSQL_SECURE_AUTH'; did you mean 'MYSQL_DEFAULT_AUTH'?
    case MYSQL_SECURE_AUTH:
         ^~~~~~~~~~~~~~~~~
         MYSQL_DEFAULT_AUTH
/usr/local/Cellar/mysql/8.0.15/include/mysql/mysql.h:188:3: note: 'MYSQL_DEFAULT_AUTH' declared here
  MYSQL_DEFAULT_AUTH,
  ^
client.c:798:7: error: use of undeclared identifier 'boolval'
      boolval = (value == Qfalse ? 0 : 1);
      ^
client.c:799:17: error: use of undeclared identifier 'boolval'
      retval = &boolval;
                ^
client.c:830:38: error: use of undeclared identifier 'boolval'
        wrapper->reconnect_enabled = boolval;
                                     ^
client.c:1185:38: error: use of undeclared identifier 'MYSQL_SECURE_AUTH'; did you mean 'MYSQL_DEFAULT_AUTH'?
  return _mysql_client_options(self, MYSQL_SECURE_AUTH, value);
                                     ^~~~~~~~~~~~~~~~~
                                     MYSQL_DEFAULT_AUTH
/usr/local/Cellar/mysql/8.0.15/include/mysql/mysql.h:188:3: note: 'MYSQL_DEFAULT_AUTH' declared here
  MYSQL_DEFAULT_AUTH,
  ^
10 errors generated.
make: *** [client.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/emmilie/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/mysql2-0.3.21 for inspection.
Results logged to /Users/emmilie/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-16/2.4.0-static/mysql2-0.3.21/gem_make.out

An error occurred while installing mysql2 (0.3.21), and Bundler cannot continue.
Make sure that `gem install mysql2 -v '0.3.21' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  mysql2
```
When I ran `gem install mysql2 -v '0.3.21' --source 'https://rubygems.org/'` as suggested, it gave me the following, plus the errors already posted above:


```
EmmiliesMacBook:mapknitter emmilie$ gem install mysql2 -v '0.3.21' --source 'https://rubygems.org/'
Building native extensions.  This could take a while...
ERROR:  Error installing mysql2:
    ERROR: Failed to build gem native extension.

    current directory: /Users/emmilie/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/mysql2-0.3.21/ex
```
Thank you and appreciate the help!

**Comment by cesswairimu** [comment]
Hello @emestabillo, which OS are you using

**Comment by emestabillo** [comment]
Hi @cesswairimu , I am using 10.14. 
Yes I've used it but it gives me `sudo: apt-get: command not found`. So then I replaced `sudo apt-get` with `brew`:
```
EmmiliesMacBook:mapknitter emmilie$ brew install bundler libmysqlclient-dev imagemagick ruby-rmagick libfreeimage3 libfreeimage-dev ruby-dev libmagickcore-dev libmagickwand-dev
Error: No available formula with the name "bundler" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
These similarly named formulae were found:
bundler-completion ✔                                      rbenv-bundler ✔
dylibbundler                                              rbenv-bundler-ruby-version ✔
To install one of them, run (for example):
  brew install bundler-completion ✔
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```
I get this after running `bundle`:
```
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    rails (~> 3.2) was resolved to 3.2.22.5, which depends on
      bundler (~> 1.0)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 1.0)', which is required by gem 'rails (~> 3.2)', in any of the sources.
```
Next, I tried `gem install bundler -v 1.0.10` , no errors
However...it crashed with the next one `bundle _1.0.10_ install`

I realize I may have to find another issue/repo. Not sure why it seems to be complicated on my end :-)

Thank you!!

**Comment by sashadev-sky** [comment]
@emestabillo I get these issues all the time so don't worry!! We can resolve them. For your mysql issue: I also have macOS 10.14 and apparently mysql is stored differently on the new OS versions so its easier to just make your own custom build. try the one below, it worked for me:
```Bash
$ bundle config --local build.mysql2 "--with-ldflags=-L/usr/local/opt/openssl/lib --with-cppflags=-I/usr/local/opt/openssl/include"
```
- Also check if you have `cmake` installed properly with Homebrew. You need that

For Bundler could be a few things: try:
1) clearing your cache 
```
$ rm -r .bundle
$ bundle install 
```
2) uninstall bundler 2 

3) clear it again

4) check exactly what bundle was used on the lockfile (at the bottom of the lockfile) and run that bundle number like you did bundle _1.0.10 ... above

Let me know if any of this helps!

**Comment by gauravano** [comment]
Hey @emestabillo, sorry for the inconvenience. We are trying hard to make the installation process easy and clearer, and we'll try our best to help you.

We would be done with cloud9 setup https://github.com/publiclab/mapknitter/pull/420 very soon. Also, for now, you can fetch the `install-script` branch on cloud9 and do the work. I can help you in getting cloud9 running. 

Thanks!

**Comment by emestabillo** [comment]
Thanks for the response @sashadev-sky @gauravano ! Still getting errors with installing locally. I may just have to wait for #420 or the cloud9 option as suggested.

**Comment by cesswairimu** [comment]
> Any fixes for this error `mapknitter/tmp/pids/passenger.3000.pid" failed (13: Permission denied) nginx: configuration file nginx.conf test failed` when starting the server

Finally found a fix for this. This is what solved it for me
```
$ sudo chmod o+w -R /tmp/*
 sudo rm /tmp/pids/server.pid
```

**Comment by gauravano** [comment]
@emestabillo have you tried @cesswairimu's solution?  If the problem still exists, let us know, we'll give you cloud9 invite and you can fetch the PR #420 and complete the setup. Thanks!

**Comment by emestabillo** [comment]
Hi @gauravano , yep still having problems. The cloud9 option might be best for now. However..I think the issue I was going to work on may already be solved #454 . (I also couldn't replicate it on the live site). Let me find another one before I bother you :-) Thank you so much for checking in!

**Comment by gauravano** [comment]
hey @emestabillo, although the issue #454 is solved, we have many more issues and we would love to have your help with them.

So, let's ask @jywarren for a cloud9 invite for you. You can use it whenever you want and as PR for setting cloud9 is not complete so you can share the cloud9 workspace with me and I can do the setup for you. 

Thanks!

**Comment by emestabillo** [comment]
Appreciate the help @guaravano!

**Comment by emestabillo** [comment]
Appreciate the help @gauravano!

**Comment by jywarren** [comment]
Just noting that the install script at https://github.com/publiclab/mapknitter/blob/main/install_cloud.sh now works at https://Codenvy.io ! It's a very easy install process. 

@emestabillo did you need an invite? I might've missed an email if you sent it to me but if you still do, please email web@publiclab.org and I can get you one! Or, try Codenvy, which doesn't need an invite! 👍

**Comment by emestabillo** [comment]
Hi @jywarren! Let me try it on Codenvy. I’ll message you if I’m still having issues. Thank you!!

**Comment by rarrunategu1** [comment]
Hello, I have tried installing on cloud 9 and on a ubuntu terminal I installed for my windows but each of them gave me the same error:
App 21975 output: Error: The application encountered the following error: Access denied for user 'mapknitter'@'localhost' (using password: YES) (Mysql2::Error)
I've signed on to Codenvy seeing as c9 will not be available after June 30th anyway but I don't understand what the install process is.  Can someone please help me?  I've worked on this endlessly to continue to get the same error result that just about everyone here is getting.  I look forward to your reply.

**Comment by kaustubh-nair** [comment]
Hey @rarrunategu1 
In order to install on Codenvy:
1. Select a new workspace with the ubuntu stack
2. Add the URL of your forked version of mapknitter under the projects section. It should be something like `https://github.com/USERNAME/mapknitter`
3. Hit create
4. Go the the directory and run `source install_cloud.sh`

This should set everything up on codenvy
If you encounter any problems let us know!
Cheers

**Comment by rarrunategu1** [comment]
@kaustubh-nair  thank you!  I finally have mapknitter on code envy but this other section to install_cloud.sh does not work for me.  This is my error - 
user@:/projects/mapknitter
$ source install_cloud.sh
bash: install_cloud.sh: No such file or directory

I've done some googling to see what that is about but it all seems very confusing.  I ran echo $PATH and this is my result in case it helps
/projects/.che/bin:/usr/local/go/bin:/usr
/lib/jvm/java-1.8.0-openjdk-amd64/bin:/us
r/local/sbin:/usr/local/bin:/usr/sbin:/us
r/bin:/sbin:/bin

I appreciate any guidance you can give me.

**Comment by jywarren** [comment]
Hm, can you run just "ls" in the current directory to show where you are?
In theory, you should be in the 'mapknitter' folder, and the
"install_cloud.sh" file should be there, since it's a copy of this
directory: https://github.com/publiclab/mapknitter/tree/main/

What do you see in your local directory when you run "ls"? Thank you!

**Comment by rarrunategu1** [comment]
Hi @jywarren,
There is a start.sh in the mapknitter folder.  I don't see a install_cloud.sh folder.

![image](https://user-images.githubusercontent.com/29240939/57031645-3a9da100-6c16-11e9-8210-9e76f663af46.png)

**Comment by jywarren** [comment]
OK, how did you set it up? I think the best way would probably be to enter the Git url like this (note that I actually want to point it at my own fork of MapKnitter):

![Screen Shot 2019-05-01 at 5 55 24 PM](https://user-images.githubusercontent.com/24359/57045124-af82d200-6c3a-11e9-8bed-111f4c2a7704.png)

(also, select "Rails" under "Select Stack")

To fork (for anyone who wants to know), you go to https://github.com/publiclab/mapknitter, and click the `Fork` button, which copies the project into your own account, so for me, it makes https://github.com/jywarren/mapknitter. Then, you have an online space corresponding to your work, and can push code there:

![Screen Shot 2019-05-01 at 5 55 42 PM](https://user-images.githubusercontent.com/24359/57045248-fb357b80-6c3a-11e9-8e87-9f8c8dea698f.png)

Then i pressed `Save`, then `Create` in the upper right corner. 

 If you log into github you can select the project this way (only if you've already forked it):

![Screen Shot 2019-05-01 at 6 03 27 PM](https://user-images.githubusercontent.com/24359/57045418-87e03980-6c3b-11e9-8b23-15b300109acd.png)

****

AHA! @rarrunategu1 I realized what happened! It assumes the default branch is `master`, but we are tending to use `main` instead of `master` on projects more and more. So, to switch and get the latest `main` branch, you can do:

`git checkout -b main && git pull https://github.com/publiclab/mapknitter main`

This will get the latest code. SORRY ABOUT THAT!!! 🎉

**Comment by jywarren** [comment]
@emestabillo @rarrunategu1 I also encountered the issue @emestabillo saw in cloud9, of:

`Bundler could not find compatible versions for gem "bundler":`

And i also tried `gem install bundler -v 1.0.10`, and after that, i was able to start it with `rails s`.

It's running now. But this is a weird question, I'm not sure how to open it in a new browser tab and interact with the site! Uh......

**Comment by jywarren** [comment]
https://github.com/codenvy/codenvy/issues/2503 ... researching...

**Comment by rarrunategu1** [comment]
@jywarren Thank you.  I was able to source install_cloud.sh, however I'm still not able to run.  I installed everything that your video says to install and in their right places and when I try to run it I'm getting errors. I did notice that the file has a database.yml and config.yml file already so I didn't copy those.  Could that cause an issue?  Here's my error: 
![image](https://user-images.githubusercontent.com/29240939/57049649-ff679600-6c46-11e9-9111-9b0ab92373d9.png)
Even when I try to run it at the top of codenvy I get this error:
![image](https://user-images.githubusercontent.com/29240939/57049686-26be6300-6c47-11e9-9e69-fdfb2ba7e690.png)  
I did try to run gem install bundler -v 1.0.10 but I don't have write permission.

**Comment by jywarren** [comment]
Ah, you're getting further than me! Your run command looks to be trying to use the `go` programming language. See if you can edit the `run` command to use `rails s -p 51656` instead of `go get && go run main.go`... now, i have to find how you got the preview URL to appear!

**Comment by jywarren** [comment]
OK, i changed my whole `run` command to, in full, `cd /projects/mapknitter && source ~/.profile && rails s -p 49286` (but you should use your own port number 51656). I got it to boot but it's not showing me the preview URL... weird...

**Comment by jywarren** [comment]
Here seems to be a good guide! https://guides.railsgirls.com/install#using-a-cloud-service

**Comment by rarrunategu1** [comment]
Thank you @jywarren .  This looks like a great guide.  I'll follow it and see what I come up with.

**Comment by jywarren** [comment]
I think the preview URL is when using the rails stack option, and you should be able to trust it rather than hunting through it as in the railsgirls.com guide -- that probably is for an older version where they didn't so conveniently show you the URL!

**Comment by jywarren** [comment]
OK! I was able to get it running by making that change to the `run` command:

`cd ${current.project.path} && source ~/.profile && rails server -b 0.0.0.0 `

![Screen Shot 2019-05-01 at 7 57 36 PM](https://user-images.githubusercontent.com/24359/57050597-74d56580-6c4b-11e9-865c-419fb3312677.png)

**Comment by jywarren** [comment]
![image](https://user-images.githubusercontent.com/24359/57050624-a0585000-6c4b-11e9-81e6-e4df657fc19b.png)

@SidharthBansal this could be a good way to test out your login changes!

**Comment by rarrunategu1** [comment]
Hi unfortunately I continue to have issues with getting it to run.  I'm getting the following error which means I don't have rails right?
![image](https://user-images.githubusercontent.com/29240939/57052792-90466d80-6c57-11e9-9a14-65ed1a5fa526.png)
So I went looking back to see what was installed and I don't see a .gem file, I can't use rvm...or bundle install..etc.... when I thought all of that was fine before.  I'll give it another go tomorrow but if anyone has come across this issue of codenvy not letting you install rails or gems please let me know.  Thank you.

**Comment by jywarren** [comment]
Ah Is your initial command "cd" need to be "cd projects/mapknitter" so you
end up in the right directory before trying to run "rails"? Maybe? I hope
that's it! Thanks!

**Comment by rarrunategu1** [comment]
Hi @jywarren , I clicked on the folder and it returned what I needed but still it gave me issues.  I restarted everything using a rails default stack instead of the go default which is what I understood we had to use.  That one went by so smoothly and I now have a running application with all of your and everyone else's directions from above.  The teamwork here is truly amazing.  Thank you so much!  Now I can dive into some of these issues.

**Comment by jywarren** [comment]
Oh, awesome to hear! Great work!

**Comment by benfanderson** [comment]
Apologies if this has already been answered but whenever I try to run ```rake db:setup``` I get the following error 
```LoadError: Please install the mysql2 adapter: `gem install activerecord-mysql2-adapter` (cannot load such file -- mysql2/mysql2)```
I have tried installing the activerecord-mysql2-adapter gem but the error remains.
The adapters in my database.yml file are all mysql2
I am running ```Ruby 2.4.6p354``` and ```Rails 3.2.22.5```

**Comment by kaustubh-nair** [comment]
@benfanderson Sorry for such a late reply... What operating system are you running?

**Comment by metonymic-smokey** [comment]
@benfanderson @kaustubh-nair I've been encountering the same issue on my local system too(Mac OS Mojave user). All my adapters are mysql2 too and I've tried the other fixes found online but this issue just persists!

**Comment by kaustubh-nair** [comment]
Hi @metonymic-smokey 
I'm tagging @sashadev-sky here. I think she can help you out with Mac OS

**Comment by metonymic-smokey** [comment]
@kaustubh-nair I'm facing an issue with the very last step, `bundle exec passenger start` , Ubuntu this time not Mac OS.
I'd used the link in the Installation and generated two keys(these keys were my second or third attempt at setting Mapknitter up) and copied them in the recaptcha.rb file.
However, when I run `passenger start`, I encounter this error:
`App 25409 output: Error: The application encountered the following error: uninitialized constant Recaptcha::ClientHelper (NameError)
`
I've tried the usual methods of searching and trying to resolve this but they didn't seem to work, so I thought I'd ask here.
Thanks!

**Comment by kaustubh-nair** [comment]
@metonymic-smokey Can you confirm that you are on the `main` branch?
And also make sure you have the latest changes by running `git pull origin main`?
And then install gems by running `bundle install`
If you still encounter the issue let me know
THanks!

**Comment by metonymic-smokey** [comment]
@kaustubh-nair @gauravano @jywarren I was on the main branch, pulled the latest changes and ran `bundle install` too.
On running, `bundle exec passenger start`, I got a different error this time:
`ActiveRecord::SchemaMigration Load (1.1ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
ActiveRecord::PendingMigrationError (
Migrations are pending. To resolve this issue, run:
	bin/rake db:migrate RAILS_ENV=development
`.
 I ran `bin/rake db:migrate RAILS_ENV=development` as suggested in the error message. 
I got this error on doing the above:
`Mysql2::Error: BLOB, TEXT, GEOMETRY or JSON column 'styles' can't have a default value: CREATE TABLE `maps` (`id` int(11) auto_increment PRIMARY KEY, `name` varchar(255) DEFAULT '', `lat` decimal(20,10) DEFAULT 0, `lon` decimal(20,10) DEFAULT 0, `zoom` decimal DEFAULT 0.02, `version` int(11) DEFAULT 1, `password` varchar(255) DEFAULT '', `styles` text DEFAULT '', `created_at` datetime, `updated_at` datetime) ENGINE=InnoDB
`.
I also followed [this](https://stackoverflow.com/questions/38433603/mysql2error-blob-text-geometry-or-json-column-body-cant-have-a-default-v) answer and also changed the RAILS_ENV in mapknitter.env to 'development'.
I tried to migrate again but got the same errors as earlier.

Thanks!

**Comment by gauravano** [comment]
Hey @metonymic-smokey, changing the sql mode is one way. There's another way: copy the content of `schema.rb.example` and using it create a new file `schema.rb`. After that, try running `rake db:migrate`.

**Comment by metonymic-smokey** [comment]
@gauravano @kaustubh-nair Thanks a lot for all the help! I have it installed locally on my system all thanks to your suggestions :) 
When it is running, the terminal displays this message: ``ActiveRecord::SchemaMigration Load (27.9ms)  SELECT `schema_migrations`.* FROM `schema_migrations` ``, is this something I should be concerned about to try and fix or just let things run as is?

Thanks once again!

**Comment by gauravano** [comment]
> ActiveRecord::SchemaMigration Load (27.9ms) SELECT `schema_migrations`.* FROM `schema_migrations`

It's normal and you shouldn't bother about this. Rails is just checking if there are any pending migrations to run or not. As you're not getting any error/warning, means there is no migration pending.

**Comment by sashadev-sky** [comment]
@benfanderson @metonymic-smokey did you guys receive these errors after following the instructions in https://github.com/publiclab/mapknitter/blob/main/MYSQL.md? 

@kaustubh-nair @alaxalves ```LoadError: Please install the mysql2 adapter: `gem install activerecord-mysql2-adapter` (cannot load such file -- mysql2/mysql2)``` is  there any way we can customize this error message to ```LoadError: cannot load such file -- mysql2/mysql2. Do not gem  install activerecord-mysql2-adapter, instead try____```

**Comment by metonymic-smokey** [comment]
@sashadev-sky Yes, I initially did follow those instructions for Mac OS but wasn't able to set it up locally.
I then switched to Ubuntu and managed to set it up with help from the community, again after following the mysql instructions and debugging a bit on my own.
Thanks!

**Comment by gauravano** [comment]
@metonymic-smokey could you tell us at which step, instructions need more clarity or the commands didn't work out well for Mac OS?

**Comment by metonymic-smokey** [comment]
@gauravano As I said above, whenever I attempted to run `rake db:setup`,I got an error with my adapters, even though on checking all of them in the database.yml file were mysql2 already.
I tried changing them to mysql but the error persisted.

**Comment by gauravano** [comment]
Hmm, ok. Thank you for details. We'll certainly try to make our installation process easier and faster.

**Comment by nstjean** [comment]
Hi! I'm installing this repo on a fresh Ubuntu installation. Everything worked very smoothly until I tried to start up the server, I'm getting an error specifiying a problem with bootsnap.

`bundle exec rails s
=> Booting Puma
=> Rails 5.2.3 application starting in development 
=> Run `rails server -h` for more startup options
W, [2019-10-07T11:16:23.731693 #29885]  WARN -- Skylight: [SKYLIGHT] [4.1.2] Running Skylight in development mode. No data will be reported until you deploy your app.
(To disable this message for all local apps, run `skylight disable_dev_warning`.)
Exiting
/home/natalie/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/compile_cache/yaml.rb:50:in `fetch': No such file or directory - bs_fetch:open_current_file:open (Errno::ENOENT)
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/compile_cache/yaml.rb:50:in `block in install!'
	from /home/natalie/Dev/Ruby/public-lab/mapknitter/config/initializers/load_config.rb:1:in `<main>'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/engine.rb:657:in `block in load_config_initializer'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/engine.rb:656:in `load_config_initializer'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/engine.rb:613:in `each'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/engine.rb:613:in `block in <class:Engine>'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /home/natalie/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /home/natalie/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/natalie/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /home/natalie/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/natalie/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `each'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /home/natalie/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/tsort.rb:415:in `call'
	from /home/natalie/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /home/natalie/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/natalie/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /home/natalie/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /home/natalie/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/natalie/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /home/natalie/.rvm/rubies/ruby-2.4.6/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
	from /home/natalie/Dev/Ruby/public-lab/mapknitter/config/environment.rb:5:in `<main>'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/skylight-core-4.1.2/lib/skylight/core/probes.rb:118:in `require'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `require_relative'
	from config.ru:3:in `block in <main>'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/rack-2.0.7/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/rack-2.0.7/lib/rack/server.rb:219:in `app'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:27:in `app'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/rack-2.0.7/lib/rack/server.rb:354:in `wrapped_app'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:51:in `start'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in `tap'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/commands/server/server_command.rb:142:in `perform'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<main>'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	from /home/natalie/.rvm/gems/ruby-2.4.6/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	from bin/rails:4:in `<main>'`

**Comment by cesswairimu** [comment]
Hi @nstjean, did u copy config/database.yml.example to config/database.yml and also db/schema.rb.example to db/schema.rb?

**Comment by nstjean** [comment]
Hi, yes I copied and saved both of those.

**Comment by cesswairimu** [comment]
could u try starting the server with passenger. `$ passenger start`

**Comment by nstjean** [comment]
Here's the screenshot of the errors I got trying `passenger start` and `passenger start --port 3001`
![natalie@natalie-ubuntu: ~-Dev-Ruby-public-lab-mapknitter_001](https://user-images.githubusercontent.com/49460529/66398364-a2b59780-e9ab-11e9-97e6-ae7d50247b6c.png)

**Comment by blurry-x-face** [comment]
Hi, I'm having trouble setting up the project locally. When I try to run `bundle exec rake db:setup` its giving the following error 
```rake aborted!
rake aborted!
Errno::ENOENT: No such file or directory - bs_fetch:open_current_file:open
/home/rs007/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/compile_cache/yaml.rb:50:in `fetch'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/compile_cache/yaml.rb:50:in `block in install!'
/home/rs007/git/mapknitter/config/initializers/load_config.rb:1:in `<main>'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/engine.rb:657:in `block in load_config_initializer'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/engine.rb:656:in `load_config_initializer'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/engine.rb:613:in `each'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/engine.rb:613:in `block in <class:Engine>'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `each'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
/home/rs007/git/mapknitter/config/environment.rb:5:in `<main>'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/skylight-core-4.1.2/lib/skylight/core/probes.rb:118:in `require'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/application.rb:337:in `require_environment!'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/railties-5.2.3/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/home/rs007/.rvm/gems/ruby-2.4.6/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/home/rs007/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `eval'
/home/rs007/.rvm/gems/ruby-2.4.6/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create => db:load_config => environment
(See full trace by running task with --trace)
```
I tried reinstalling mysql server still i'm getting the same error I'm stuck on this for 2 days now!

**Comment by stefanosu** [comment]
Hello, everyone, I'm having trouble setting up the project locally. When I try to run rails s to get the server running. I get this error: Could not find libxml-ruby-3.1.0 in any of the sources
Run `bundle install` to install missing gems. Then when I bundle install I get this error: ```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/stefanosugbit/.rvm/gems/ruby-2.5.0/gems/libxml-ruby-3.1.0/ext/libxml
/Users/stefanosugbit/.rvm/rubies/ruby-2.5.0/bin/ruby -I /Users/stefanosugbit/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0 -r ./siteconf20191011-12959-rqd4ud.rb extconf.rb
/Users/stefanosugbit/.rvm/rubies/ruby-2.5.0/bin/ruby: warning: shebang line ending with \r may cause problems
checking for libxml/xmlversion.h in /opt/include/libxml2,/opt/local/include/libxml2,/usr/local/include/libxml2,/usr/include/libxml2... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/stefanosugbit/.rvm/rubies/ruby-2.5.0/bin/$(RUBY_BASE_NAME)
	--with-xml2-config
	--without-xml2-config
	--with-xml2-dir
	--without-xml2-dir
	--with-xml2-include
	--without-xml2-include=${xml2-dir}/include
	--with-xml2-lib
	--without-xml2-lib=${xml2-dir}/lib
 extconf failure: need libxml2.

    Install the library or try one of the following options to extconf.rb:

      --with-xml2-config=/path/to/xml2-config
      --with-xml2-dir=/path/to/libxml2
      --with-xml2-lib=/path/to/libxml2/lib
      --with-xml2-include=/path/to/libxml2/include


To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/stefanosugbit/.rvm/gems/ruby-2.5.0/extensions/x86_64-darwin-18/2.5.0/libxml-ruby-3.1.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/stefanosugbit/.rvm/gems/ruby-2.5.0/gems/libxml-ruby-3.1.0 for inspection.
Results logged to /Users/stefanosugbit/.rvm/gems/ruby-2.5.0/extensions/x86_64-darwin-18/2.5.0/libxml-ruby-3.1.0/gem_make.out

An error occurred while installing libxml-ruby (3.1.0), and Bundler cannot continue.
Make sure that `gem install libxml-ruby -v '3.1.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  right_aws_api was resolved to 0.3.5, which depends on
    right_cloud_api_base was resolved to 0.2.6, which depends on
      libxml-ruby
```

**Comment by cesswairimu** [comment]
Hi @nstjean @blurry-x-face , did you get your issues fixed yet? @stefanosu  try running `gem install libxml-ruby -v '3.1.0' --source 'https://rubygems.org/'`

**Comment by stefanosu** [comment]
@cesswairimu Yea I tried that and I still get that same error.  :(

**Comment by cesswairimu** [comment]
Did you have ruby and rails working well in your environment before?

**Comment by stefanosu** [comment]
No, I didn't I made the changes to the code in the browser.

**Comment by blurry-x-face** [comment]
> Hi @nstjean @blurry-x-face , did you get your issues fixed yet? @stefanosu try running `gem install libxml-ruby -v '3.1.0' --source 'https://rubygems.org/'`

No, I didn't

**Comment by nstjean** [comment]
I got mine running today!!

**Comment by cesswairimu** [comment]
Great @nstjean,  do you mind please posting your solution? I believe @blurry-x-face was facing the same problem...or in future anyone might get the same prob. Thanks

**Comment by cesswairimu** [comment]
@blurry-x-face which OS are you using?

**Comment by cesswairimu** [comment]
@stefanosu  I believe you are running on linux right?

**Comment by cesswairimu** [comment]
@stefanosu  try running this `sudo apt-get install libxslt-dev libxml2-dev` after it succeeds try doing `bundle install` again

**Comment by stefanosu** [comment]
I'm running on mac OS.

**Comment by cesswairimu** [comment]
ooh cool...should work for Mac too please try the command :point_up:

**Comment by nstjean** [comment]
@cesswairimu Sure!

First I made sure the config files were properly copied, renamed, and saved. I think one of mine might have been incorrect.
I double checked my re-captcha keys, those were ok.
I re-installed assets with `yarn install`
Then I tried `bundle exec rails s` again and it didn't give me an error.

I'm guessing something in database.yml or config.yml were wrong.

**Comment by stefanosu** [comment]
I tried running it says command not found and I also tried to add this extension to it STATIC_DEPS=true sudo pip install lxml

**Comment by cesswairimu** [comment]
Thanks @nstjean :+1:

**Comment by cesswairimu** [comment]
@stefanosu could you take a look at this thread see if any of these will sort out your issues? You could also go through this to make sure you have ruby and rails installed correctly

**Comment by stefanosu** [comment]
Thanks, @cesswairimu for your help I'll comb through those threads. I feel like I'm close to getting it to work.

**Comment by blurry-x-face** [comment]
Thanks @nstjean and @cesswairimu I also had the same error as you, its working now yay!

**Comment by stefanosu** [comment]
Hey, I'm everyone I'm still stuck on getting the rails server to run. I went through all those threads and still having trouble getting it to run. @cesswairimu

**Comment by cesswairimu** [comment]
Hi @stefanosu so sorry about that... What is the error you are getting... Same error you posted above?

**Comment by stefanosu** [comment]
hey no worries no I'm getting another error this is what I'm getting now: when I try running rails s I get this error: /Users/stefanosugbit/.rvm/gems/ruby-2.5.0/gems/bootsnap-1.4.5/lib/bootsnap/compile_cache/yaml.rb:50:in `fetch': No such file or directory - bs_fetch:open_current_file:open (Errno::ENOENT)

**Comment by cesswairimu** [comment]
Aha... Please  make sure you have copied `database.yml`and `config.yml` are copied correctly aee  @nstjean comment above of the solution.. Was facing the same issue you are pretty close :crossed_fingers:

**Comment by stefanosu** [comment]
@nstjean Hey it seems that I'm having the same error you are but I'm having trouble implementing the steps you've done to arrive at fixing the issue. Did you make sure that the config files were properly copied the same as they were from the repo?

**Comment by jywarren** [comment]
Hi all, i had some trouble booting this and traced it to the `bootsnap` gem, which does caching to speed up application boot. I was able to bypass it by commenting out line 4 of `config/boot.rb`:

```ruby
require 'bootsnap/setup' # Speed up boot time by caching expensive operations.
```

**Comment by chepyego** [comment]
am having trouble setting up my database though am able to acces mysql with `mysql -u root -p`  but when i ran 'bundle exec rails db:setup` am getting this error  'How to Solve MySQL Error: Access denied for user root@localhost` i have tried the proposed solutions above but still getting same error

**Comment by PeculiarE** [comment]
Hello @chepyego. Most times, that error is thrown if you haven't configured your database correctly in the `database.yml` file. Could you please confirm that the username and password for your development database is correctly inputted?

**Comment by chepyego** [comment]
Hello @PeculiarE i managed to fix it by changing the test_database password and username to be the same as the development database. But am having another problem I can attach a screenshot below
![yarnerror](https://user-images.githubusercontent.com/22706319/161525812-e52a84b6-7bab-49cb-9ba9-8c8c91adb38f.png)

**Comment by PeculiarE** [comment]
Nicey. Well done 😄 😄 @chepyego. Please check out this stackoverflow thread to fix the incompatible module issue: https://stackoverflow.com/questions/56617209/the-engine-node-is-incompatible-with-this-module.

**Comment by chepyego** [comment]
> Nicey. Well done smile smile @chepyego. Please check out this stackoverflow thread to fix the incompatible module issue: https://stackoverflow.com/questions/56617209/the-engine-node-is-incompatible-with-this-module.

am getting twosolution one is to run `yarn install --ignore-engines` and another one is to delete(delete node_modules/, package-lock.json & yarn.lock) and run yarn install .Am not sure which should I go with, @PeculiarE  what is your take here?

**Comment by cesswairimu** [comment]
Hi @chepyego ,  you could give this solution a try 
```
sudo apt-get purge --auto-remove nodejs
curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**Comment by chepyego** [comment]
> Hi @chepyego, you could give this solution a try
> 
> ```
> sudo apt-get purge --auto-remove nodejs
> curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
> sudo apt-get install -y nodejs
> ```

hey @cesswairimu  i think I have managed to solve the issue I installed node v16 and set nvm to use this version then I `yarn install ` and I didn't receive any errors

**Comment by chepyego** [comment]
![mapknitter](https://user-images.githubusercontent.com/22706319/161709678-a17972ee-5806-4479-942b-a720975fb2f2.png)
it is up and running

**Comment by chepyego** [comment]
Thank you @PeculiarE and @cesswairimu for your help

**Comment by chepyego** [comment]
just a quick question @cesswairimu  how do we login in using data in seed.rb I haven't understood from the installation guide

**Comment by cesswairimu** [comment]
@chepyego  if you have already ran `rake db:seed` (_ run it if not_) you can navigate to this url locally and you should be logged in `http://localhost:3000/local/harry`

**Comment by PeculiarE** [comment]
You're welcome @chepyego 😄 ...I'm glad it's working now for you

**Comment by PeculiarE** [comment]
@cesswairimu .....please, I have a question. If we want to run the app on gitpod, do we need either mysql2 or sqlite3 already installed on our PCs?

**Comment by chepyego** [comment]
> @chepyego if you have already ran `rake db:seed` (_run it if not_) you can navigate to this url locally and you should be logged in `http://localhost:3000/local/harry`

just ran rake db:seed  and I get this huge error which I can't seem to get solution since yesterday (Mysql2::Error: Duplicate entry '82' for key 'warpables.PRIMARY)

**Comment by PeculiarE** [comment]
Hi @chepyego...I replied your inquiry on this same issue in the gitter chatroom, but I dunno if you saw it. So I'm just going to repost it here incase you didn't and also to help anyone else who might have this issue in the future.

Here's my best guess: You probably already ran `rake db:setup` when setting up the project on your PC. I'm not so familiar with Rake, so had to go do my research. Found out that calling the command `rake db:setup` actually tells your PC to run three commands in succession: `db:create`, `db:schema:load`, and `db:seed`.

As you can see, you've already seeded your db when you ran the `db:setup` command. So running the db:seed command throws the duplicate error you received.

Hope this makes sense/helps!

**Comment by chepyego** [comment]
> > just ran rake db:seed and I get this huge error which I can't seem to get solution since yesterday (Mysql2::Error: Duplicate entry '82' for key 'warpables.PRIMARY)
> 
> Hi @chepyego...I replied your inquiry on this same issue in the gitter chatroom, but I dunno if you saw it. So I'm just going to repost it here incase you didn't and also to help anyone else who might have this issue in the future.
> 
> Here's my best guess: You probably already ran `rake db:setup` when setting up the project on your PC. I'm not so familiar with Rake, so had to go do my research. Found out that calling the command `rake db:setup` actually tells your PC to run three commands in succession: `db:create`, `db:schema:load`, and `db:seed`.
> 
> As you can see, you've already seeded your db when you ran the `db:setup` command. So running the `db:seed` command after already running `rake db:setup` throws the duplicate error you received.
> 
> Hope this makes sense/helps!

hey, I guess i didn't see your comment, your point makes sense and is very helpful . i can now make my first PR

**Comment by chepyego** [comment]
but still i can't login in the browser with those credentials in in seed.rb

**Comment by PeculiarE** [comment]
What's the error you get?

**Comment by chepyego** [comment]
> What's the error you get?

it is not an error but am trying to login in URL using this `http://localhost:3000/local/harry` where `harry` is the username and it is in our seed.rb but nothings happens . i don't know if this is how it is suppose to be

**Comment by chepyego** [comment]
hey I just ran this I copied from the documentation  `http://localhost:3000/local/harry ` and it has worked although I don't see any difference with the one above. Am now good to go  thanks a lot again you have really helped me

**Comment by PeculiarE** [comment]
You're welcome 😃 ❤️ ....glad you're up and running now 🚀

**Comment by chepyego** [comment]
> You're welcome smiley heart ....glad you're up and running now rocket

yes am happy too I hope am that late to start making my contributions

**Comment by PeculiarE** [comment]
It basically stands for first-timer-only. It's a label given to issues. An FTO issue is specially curated for first-timers, that is, newbies to the project/codebase.

In an FTO issue, the problem and solution are given to you. All you have to do is implement it by following the instructions given. Solving an FTO issue gets you familiar with the project's version control, starts helping you get familiar with the codebase, and of course, gives you a sense of confidence. Once you're done with solving an FTO, you can progress into looking for a bit more complex issues (e.g. issues with labels such as help-wanted, bug etc.). These issues don't yet have solutions; you have to provide it. You can even start creating FTOs for others.

**Comment by chepyego** [comment]
> It basically stands for first-timer-only and is a label given to issues. An FTO issue is specially curated for first-timers, that is, newbies to the project/codebase.
> 
> In an FTO issue, the problem and solution are given to you. All you have to do is implement it by following the instructions given. Solving an FTO issue gets you familiar with the project's version control, starts helping you get familiar with the codebase, and of course, gives you a sense of confidence. Once you're done with solving an FTO, you can progress into looking for a bit more complex issues (e.g. issues with labels such as help-wanted, bug etc.). These issues don't yet have solutions; you have to provide it. You can even start creating FTOs for others.

okay got it, am an outreachy applicant and plot2 is not part of the outreachy project and I would like to work on this mapknitter project ,I guess I can find some FTO tickets in mapknitter too, or is it a must to work on FTO in publiclab/plot2 project?

**Comment by cesswairimu** [comment]
hi all, you are right @chepyego,  you do not work on plots2 project , you could just work on mapknitter only. I really love the great collaboration here. Many thanks everyone for helping each other and helping out :heart: :heart:
