### ISSUE TITLE
Unstable branch usage for Rails upgrade

### ISSUE THREAD

**Issue by kaustubh-nair** [publiclab/mapknitter#665]
Current proposal:
* Publish Rails upgrade to `unstable`
* Test and fix issues in small self-contained PRs 
* Review PRs and merge again to `unstable`
* Maintain a work in progress PR from `unstable` to `main`
* Rebase WIP PR every 1-2 days (depends on frequency of fixes)

**Comment by kaustubh-nair** [comment]
@cesswairimu @alaxalves @jywarren @sashadev-sky @SidharthBansal

**Comment by cesswairimu** [comment]
Hey @kaustubh-nair, thanks for creating this. Great plan..I will create an issue for reporting bugs. Is it okay if I push to unstable right now @jywarren. Thanks all.

**Comment by alaxalves** [comment]
@cesswairimu Maybe you could open #578 to our unstable branch, I think that we could go further/faster with our work by doing that. Currently our work is very "slip up", and I think it's time we start integrating.

@publiclab/reviewers @publiclab/maintainers @sashadev-sky @jywarren @icarito @SidharthBansal could yall give your opinion here?

**Comment by alaxalves** [comment]
Ok, so @cesswairimu @kaustubh-nair I have just created a branch named `development` so support this planning of ours. I'll merge #578 on top of this branch, and we all could open PR's/merge ou work to it, instead of the `main` branch.

**Comment by alaxalves** [comment]
I'll work on the problematic tests and the rubocop offenses, I will create a PR to development after its done so you can check it out. The same goes for you guys, from now on we create branches from development branch and open PR to it. Meanwhile we could open a WIP PR from development to main, so that the mentors and community could keep track of what we're doing.

**Comment by cesswairimu** [comment]
Hey @alaxalves am almost done with the codeclimate issues please take a look at the failing test that's what's left.  thanks

**Comment by alaxalves** [comment]
> Hey @alaxalves am almost done with the codeclimate issues please take a look at the failing test that's what's left. thanks

@cesswairimu Check https://github.com/publiclab/mapknitter/pull/667, then publish your work on top of it.

**Comment by jywarren** [comment]
Should be fine to publish to unstable as much as you need! Thanks!

**Comment by sashadev-sky** [comment]
Sounds like a plan!

**Comment by alaxalves** [comment]
BTW @cesswairimu I have fixed the problematic test at #667 and fixed some minor offeses. If you and @kaustubh-nair please review that. :)

**Comment by alaxalves** [comment]
![image](https://user-images.githubusercontent.com/19597045/58987957-fd00da80-87b6-11e9-80c4-f5a214993df4.png)
:tada: :tada: :tada: :tada:

**Comment by jywarren** [comment]
Awesome!!!

**Comment by cesswairimu** [comment]
@alaxalves https://github.com/publiclab/mapknitter/tree/development is failing on unstable with
![Screenshot from 2019-06-10 17-38-40](https://user-images.githubusercontent.com/17081074/59203171-b50ef880-8ba6-11e9-9c61-adc1330b63d8.png)
Not sure what the error is but I guess its not safe to merge it to main we will have the other branch merged if that's okay with you so that I can unblock you guys and can go on with your work. Thanks

**Comment by kaustubh-nair** [comment]
@cesswairimu I tried to clean some older commits and push to `unstable` but it is still broken
@jywarren Would it be possible to pull up the logs when you have time? Thanks

**Comment by jywarren** [comment]
Hi all, i believe the startup log output is available at
https://jenkins.laboratoriopublico.org, but if not, ping me and I can look
on the server itself!

**Comment by kaustubh-nair** [comment]
Got it thanks :+1: 
@cesswairimu Have you encountered this error before during the upgrade? If not I'll look into it.
https://jenkins.laboratoriopublico.org/job/Mapknitter-Unstable/79/console

**Comment by cesswairimu** [comment]
No I haven't.

**Comment by jywarren** [comment]
Do we need to correct https://github.com/publiclab/mapknitter/#staging-infrastructure-and-testing to say that `main` is linked to `stable` but `unstable` is linked to `unstable`?

**Comment by jywarren** [comment]
Also noting that @rarrunategu1 has just pushed to `unstable` but there seems to be an issue with the `chalk` js library... 

https://jenkins.laboratoriopublico.org/

here's the log output for that build: https://jenkins.laboratoriopublico.org/job/Mapknitter-Unstable/81/console

`Uglifier::Error: Unexpected token: name (TemplateStringsArray)`

any ideas?

**Comment by alaxalves** [comment]
> @alaxalves https://github.com/publiclab/mapknitter/tree/development is failing on unstable with
> ![Screenshot from 2019-06-10 17-38-40](https://user-images.githubusercontent.com/17081074/59203171-b50ef880-8ba6-11e9-9c61-adc1330b63d8.png)
> Not sure what the error is but I guess its not safe to merge it to main we will have the other branch merged if that's okay with you so that I can unblock you guys and can go on with your work. Thanks

Yes, Cess the idea is only merging to main when we get it all working with Rails 6, so it'll take a lil time to merge it to main branch. The idea is keep hotfixing development with Rails 6 until it gets stable enough to get to main.

**Comment by kaustubh-nair** [comment]
What is the idea behind waiting till Rails 6 ? @alaxalves ?

**Comment by kaustubh-nair** [comment]
Anyway, `unstable` seems to be up with Rails 4 right now. Might have been some problems with older commits

**Comment by cesswairimu** [comment]
That is still from branch #578 `development` is still failing

**Comment by kaustubh-nair** [comment]
And the Gemfile.lock was different as well.
I see the problem now
```
rake aborted!
NameError: uninitialized constant Recaptcha::ClientHelper
/app/config/initializers/recaptcha.rb:4:in `<class:Base>'
/app/config/initializers/recaptcha.rb:3:in `<top (required)>'
/usr/local/bundle/gems/railties-4.2.11.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
/usr/local/bundle/gems/activesupport-4.2.11.1/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/railties-4.2.11.1/lib/rails/engine.rb:651:in `load_config_initializer'
/usr/local/bundle/gems/railties-4.2.11.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr
```
This is the error on unstable for `development`
@alaxalves Please don't run `bundle update` without testing rigorously. The Recaptcha version bump in this commit https://github.com/publiclab/mapknitter/commit/5bb19c2ec8264d1b0a53855809a5fe3645f0af82 is causing the problem

**Comment by kaustubh-nair** [comment]
I've pushed `development` to `unstable` @cesswairimu

**Comment by alaxalves** [comment]
@kaustubh-nair I dont remember bundle updating on Mapknitter, maybe dependa-bot? Anyway if it was me I'm sorry. The schema file was not manually changed, actually it has been changed because we have adopted the same stylesheet as Plots2, so Rubocop has autofixed it. 
I didn't mean we wait for Rails 6, I mean we keep updating development branch until it gets stable.

**Comment by alaxalves** [comment]
I'll close since we agreed on using `development` branch.
